FROM python:3.12-slim

WORKDIR /app

ARG TENTACLE_LIDARR_URL=http://lidarr:8686
ARG TENTACLE_LIDARR_API_KEY=
ARG TENTACLE_DOWNLOAD_PATH=/music
ARG TENTACLE_DOWNLOAD_QUALITY=LOSSLESS
ARG TENTACLE_SERVICE_SCAN_INTERVAL_MINUTES=15

ENV TENTACLE_LIDARR_URL=${TENTACLE_LIDARR_URL} \
    TENTACLE_LIDARR_API_KEY=${TENTACLE_LIDARR_API_KEY} \
    TENTACLE_DOWNLOAD_PATH=${TENTACLE_DOWNLOAD_PATH} \
    TENTACLE_DOWNLOAD_QUALITY=${TENTACLE_DOWNLOAD_QUALITY} \
    TENTACLE_SERVICE_SCAN_INTERVAL_MINUTES=${TENTACLE_SERVICE_SCAN_INTERVAL_MINUTES}

COPY pyproject.toml .
COPY tentacle/ tentacle/

RUN pip install --no-cache-dir . \
    && mkdir -p /config /music

VOLUME ["/config", "/music"]

ENTRYPOINT ["tentacle"]
CMD ["--config", "/config/config.yml"]
